import type { WatermarkPreset } from "../../types/watermark";

export const watermarkPresets: WatermarkPreset[] = [
  {
    id: "confidential",
    name: "Confidential",
    description: "Large diagonal text for controlled document circulation.",
    config: {
      type: "text",
      text: "CONFIDENTIAL",
      rotation: 45,
      opacity: 0.18,
      fontSize: 64,
      positionPreset: "center",
      pages: { mode: "all", selection: "" },
    },
  },
  {
    id: "internal-use-only",
    name: "Internal Use Only",
    description: "Moderate center watermark for internal documentation.",
    config: {
      type: "text",
      text: "INTERNAL USE ONLY",
      rotation: 35,
      opacity: 0.14,
      fontSize: 52,
      positionPreset: "center",
      pages: { mode: "all", selection: "" },
    },
  },
  {
    id: "draft-review",
    name: "Draft Review",
    description: "Repeated draft pattern for review packets.",
    config: {
      type: "pattern",
      text: "DRAFT",
      rotation: 45,
      opacity: 0.12,
      fontSize: 38,
      patternSpacingX: 220,
      patternSpacingY: 160,
      patternStaggered: true,
      pages: { mode: "all", selection: "" },
    },
  },
  {
    id: "classified",
    name: "Classified",
    description: "Top and bottom classification banners.",
    config: {
      type: "classification-banner",
      classificationText: "CLASSIFIED",
      text: "CLASSIFIED",
      bannerEnabledTop: true,
      bannerEnabledBottom: true,
      classificationTop: true,
      classificationBottom: true,
      opacity: 0.92,
      fontSize: 14,
      pages: { mode: "all", selection: "" },
    },
  },
  {
    id: "legal-copy",
    name: "Legal Copy",
    description: "Low-opacity legal circulation watermark.",
    config: {
      type: "text",
      text: "LEGAL COPY",
      rotation: 45,
      opacity: 0.16,
      fontSize: 58,
      positionPreset: "center",
      pages: { mode: "all", selection: "" },
    },
  },
  {
    id: "reviewed-seal",
    name: "Reviewed Seal",
    description: "Document control seal for completed review.",
    config: {
      type: "seal",
      sealTitle: "REVIEWED",
      sealSubtitle: "DOCUMENT CONTROL",
      sealShowDate: true,
      sealBorderThickness: 2,
      opacity: 0.75,
      rotation: 0,
      positionPreset: "bottom-right",
      pages: { mode: "all", selection: "" },
    },
  },
  {
    id: "logo-centered",
    name: "Logo Centered",
    description: "Image watermark structure for centered organization marks.",
    config: {
      type: "image",
      opacity: 0.22,
      scale: 0.35,
      rotation: 0,
      positionPreset: "center",
      pages: { mode: "all", selection: "" },
    },
  },
  {
    id: "repeated-diagonal",
    name: "Repeated Diagonal",
    description: "Dense repeated diagonal text pattern.",
    config: {
      type: "pattern",
      text: "CONFIDENTIAL",
      rotation: 45,
      opacity: 0.1,
      fontSize: 32,
      patternSpacingX: 180,
      patternSpacingY: 140,
      patternStaggered: true,
      pages: { mode: "all", selection: "" },
    },
  },
];
